name: E2E Upload & Worker Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y netcat docker-compose

      - name: Start local infra (Postgres + MinIO)
        run: |
          docker-compose -f infra/docker-compose.yml up -d --build

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "Postgres is up"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done
          echo "Postgres did not start in time" >&2
          exit 1

      - name: Wait for MinIO
        run: |
          for i in {1..30}; do
            if nc -z localhost 9000; then
              echo "MinIO is up"
              exit 0
            fi
            echo "Waiting for MinIO..."
            sleep 2
          done
          echo "MinIO did not start in time" >&2
          exit 1

      - name: Ensure MinIO bucket and apply DB migration
        run: |
          # Ensure bucket (script should handle idempotency)
          node packages/api/scripts/create_minio_bucket.js || echo "create_minio_bucket.js returned non-zero (continuing)"

          # Find the postgres container started by docker-compose
          POSTGRES_CONTAINER=$(docker ps --filter "ancestor=postgres:15-alpine" --format "{{.Names}}" | head -n1)
          if [ -n "$POSTGRES_CONTAINER" ]; then
            echo "Applying migration to $POSTGRES_CONTAINER"
            docker exec -i $POSTGRES_CONTAINER sh -c 'psql -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}' < infra/migrations/001_create_evidence.sql
          else
            echo "Postgres container not found; failing"
            exit 1
          fi

      - name: Run sanitizeEnv unit tests
        run: |
          node infra/tests/run_sanitize_env_test.js

      - name: Write env hex dumps (for validator and forensics)
        run: |
          node infra/scripts/write_env_hex.js

      - name: Validate env hex dumps (fail-fast on invisible/control bytes)
        run: |
          node infra/tests/validate_env_hex.js

      - name: Run docker-compose demo-runner (presign -> upload -> index)
        run: |
          # demo-runner is a one-shot service that requests a presigned PUT URL, uploads the bundled sample,
          # and polls Postgres for the evidence row to reach status = "indexed".
          docker-compose -f infra/docker-compose.yml run --rm demo-runner

      - name: Upload debug logs (on failure)
        if: failure()
        run: |
          docker-compose -f infra/docker-compose.yml logs --no-color > e2e-logs.txt || true
          cat e2e-logs.txt || true

      - name: Tear down infra
        if: always()
        run: docker-compose -f infra/docker-compose.yml down -v
